# Generated by Django 3.2.6 on 2021-10-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmtest', '0004_author_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
